// Countries, door-opener visas, and Schengen members
// Ported from DoINeedAVisa-Website/src/data/countries.ts and doorOpenerVisas.ts

var DINAV_COUNTRIES = [
  { code: 'AF', iso3: 'AFG', name: 'Afghanistan' },
  { code: 'AL', iso3: 'ALB', name: 'Albania' },
  { code: 'DZ', iso3: 'DZA', name: 'Algeria' },
  { code: 'AD', iso3: 'AND', name: 'Andorra' },
  { code: 'AO', iso3: 'AGO', name: 'Angola' },
  { code: 'AG', iso3: 'ATG', name: 'Antigua and Barbuda' },
  { code: 'AR', iso3: 'ARG', name: 'Argentina' },
  { code: 'AM', iso3: 'ARM', name: 'Armenia' },
  { code: 'AU', iso3: 'AUS', name: 'Australia' },
  { code: 'AT', iso3: 'AUT', name: 'Austria' },
  { code: 'AZ', iso3: 'AZE', name: 'Azerbaijan' },
  { code: 'BS', iso3: 'BHS', name: 'Bahamas' },
  { code: 'BH', iso3: 'BHR', name: 'Bahrain' },
  { code: 'BD', iso3: 'BGD', name: 'Bangladesh' },
  { code: 'BB', iso3: 'BRB', name: 'Barbados' },
  { code: 'BY', iso3: 'BLR', name: 'Belarus' },
  { code: 'BE', iso3: 'BEL', name: 'Belgium' },
  { code: 'BZ', iso3: 'BLZ', name: 'Belize' },
  { code: 'BJ', iso3: 'BEN', name: 'Benin' },
  { code: 'BT', iso3: 'BTN', name: 'Bhutan' },
  { code: 'BO', iso3: 'BOL', name: 'Bolivia' },
  { code: 'BA', iso3: 'BIH', name: 'Bosnia and Herzegovina' },
  { code: 'BW', iso3: 'BWA', name: 'Botswana' },
  { code: 'BR', iso3: 'BRA', name: 'Brazil' },
  { code: 'BN', iso3: 'BRN', name: 'Brunei' },
  { code: 'BG', iso3: 'BGR', name: 'Bulgaria' },
  { code: 'BF', iso3: 'BFA', name: 'Burkina Faso' },
  { code: 'BI', iso3: 'BDI', name: 'Burundi' },
  { code: 'KH', iso3: 'KHM', name: 'Cambodia' },
  { code: 'CM', iso3: 'CMR', name: 'Cameroon' },
  { code: 'CA', iso3: 'CAN', name: 'Canada' },
  { code: 'CV', iso3: 'CPV', name: 'Cabo Verde' },
  { code: 'CF', iso3: 'CAF', name: 'Central African Republic' },
  { code: 'TD', iso3: 'TCD', name: 'Chad' },
  { code: 'CL', iso3: 'CHL', name: 'Chile' },
  { code: 'CN', iso3: 'CHN', name: 'China' },
  { code: 'CO', iso3: 'COL', name: 'Colombia' },
  { code: 'KM', iso3: 'COM', name: 'Comoros' },
  { code: 'CG', iso3: 'COG', name: 'Congo' },
  { code: 'CD', iso3: 'COD', name: 'Congo (Democratic Republic)' },
  { code: 'CR', iso3: 'CRI', name: 'Costa Rica' },
  { code: 'CI', iso3: 'CIV', name: "Cote d'Ivoire" },
  { code: 'HR', iso3: 'HRV', name: 'Croatia' },
  { code: 'CU', iso3: 'CUB', name: 'Cuba' },
  { code: 'CY', iso3: 'CYP', name: 'Cyprus' },
  { code: 'CZ', iso3: 'CZE', name: 'Czechia' },
  { code: 'DK', iso3: 'DNK', name: 'Denmark' },
  { code: 'DJ', iso3: 'DJI', name: 'Djibouti' },
  { code: 'DM', iso3: 'DMA', name: 'Dominica' },
  { code: 'DO', iso3: 'DOM', name: 'Dominican Republic' },
  { code: 'EC', iso3: 'ECU', name: 'Ecuador' },
  { code: 'EG', iso3: 'EGY', name: 'Egypt' },
  { code: 'SV', iso3: 'SLV', name: 'El Salvador' },
  { code: 'GQ', iso3: 'GNQ', name: 'Equatorial Guinea' },
  { code: 'ER', iso3: 'ERI', name: 'Eritrea' },
  { code: 'EE', iso3: 'EST', name: 'Estonia' },
  { code: 'SZ', iso3: 'SWZ', name: 'Eswatini' },
  { code: 'ET', iso3: 'ETH', name: 'Ethiopia' },
  { code: 'FJ', iso3: 'FJI', name: 'Fiji' },
  { code: 'FI', iso3: 'FIN', name: 'Finland' },
  { code: 'FR', iso3: 'FRA', name: 'France' },
  { code: 'GA', iso3: 'GAB', name: 'Gabon' },
  { code: 'GM', iso3: 'GMB', name: 'Gambia' },
  { code: 'GE', iso3: 'GEO', name: 'Georgia' },
  { code: 'DE', iso3: 'DEU', name: 'Germany' },
  { code: 'GH', iso3: 'GHA', name: 'Ghana' },
  { code: 'GR', iso3: 'GRC', name: 'Greece' },
  { code: 'GD', iso3: 'GRD', name: 'Grenada' },
  { code: 'GT', iso3: 'GTM', name: 'Guatemala' },
  { code: 'GN', iso3: 'GIN', name: 'Guinea' },
  { code: 'GW', iso3: 'GNB', name: 'Guinea-Bissau' },
  { code: 'GY', iso3: 'GUY', name: 'Guyana' },
  { code: 'HT', iso3: 'HTI', name: 'Haiti' },
  { code: 'HN', iso3: 'HND', name: 'Honduras' },
  { code: 'HK', iso3: 'HKG', name: 'Hong Kong' },
  { code: 'HU', iso3: 'HUN', name: 'Hungary' },
  { code: 'IS', iso3: 'ISL', name: 'Iceland' },
  { code: 'IN', iso3: 'IND', name: 'India' },
  { code: 'ID', iso3: 'IDN', name: 'Indonesia' },
  { code: 'IR', iso3: 'IRN', name: 'Iran' },
  { code: 'IQ', iso3: 'IRQ', name: 'Iraq' },
  { code: 'IE', iso3: 'IRL', name: 'Ireland' },
  { code: 'IL', iso3: 'ISR', name: 'Israel' },
  { code: 'IT', iso3: 'ITA', name: 'Italy' },
  { code: 'JM', iso3: 'JAM', name: 'Jamaica' },
  { code: 'JP', iso3: 'JPN', name: 'Japan' },
  { code: 'JO', iso3: 'JOR', name: 'Jordan' },
  { code: 'KZ', iso3: 'KAZ', name: 'Kazakhstan' },
  { code: 'KE', iso3: 'KEN', name: 'Kenya' },
  { code: 'KI', iso3: 'KIR', name: 'Kiribati' },
  { code: 'KP', iso3: 'PRK', name: 'North Korea' },
  { code: 'KR', iso3: 'KOR', name: 'South Korea' },
  { code: 'KW', iso3: 'KWT', name: 'Kuwait' },
  { code: 'KG', iso3: 'KGZ', name: 'Kyrgyzstan' },
  { code: 'LA', iso3: 'LAO', name: 'Laos' },
  { code: 'LV', iso3: 'LVA', name: 'Latvia' },
  { code: 'LB', iso3: 'LBN', name: 'Lebanon' },
  { code: 'LS', iso3: 'LSO', name: 'Lesotho' },
  { code: 'LR', iso3: 'LBR', name: 'Liberia' },
  { code: 'LY', iso3: 'LBY', name: 'Libya' },
  { code: 'LI', iso3: 'LIE', name: 'Liechtenstein' },
  { code: 'LT', iso3: 'LTU', name: 'Lithuania' },
  { code: 'LU', iso3: 'LUX', name: 'Luxembourg' },
  { code: 'MO', iso3: 'MAC', name: 'Macau' },
  { code: 'MG', iso3: 'MDG', name: 'Madagascar' },
  { code: 'MW', iso3: 'MWI', name: 'Malawi' },
  { code: 'MY', iso3: 'MYS', name: 'Malaysia' },
  { code: 'MV', iso3: 'MDV', name: 'Maldives' },
  { code: 'ML', iso3: 'MLI', name: 'Mali' },
  { code: 'MT', iso3: 'MLT', name: 'Malta' },
  { code: 'MH', iso3: 'MHL', name: 'Marshall Islands' },
  { code: 'MR', iso3: 'MRT', name: 'Mauritania' },
  { code: 'MU', iso3: 'MUS', name: 'Mauritius' },
  { code: 'MX', iso3: 'MEX', name: 'Mexico' },
  { code: 'FM', iso3: 'FSM', name: 'Micronesia' },
  { code: 'MD', iso3: 'MDA', name: 'Moldova' },
  { code: 'MC', iso3: 'MCO', name: 'Monaco' },
  { code: 'MN', iso3: 'MNG', name: 'Mongolia' },
  { code: 'ME', iso3: 'MNE', name: 'Montenegro' },
  { code: 'MA', iso3: 'MAR', name: 'Morocco' },
  { code: 'MZ', iso3: 'MOZ', name: 'Mozambique' },
  { code: 'MM', iso3: 'MMR', name: 'Myanmar' },
  { code: 'NA', iso3: 'NAM', name: 'Namibia' },
  { code: 'NR', iso3: 'NRU', name: 'Nauru' },
  { code: 'NP', iso3: 'NPL', name: 'Nepal' },
  { code: 'NL', iso3: 'NLD', name: 'Netherlands' },
  { code: 'NZ', iso3: 'NZL', name: 'New Zealand' },
  { code: 'NI', iso3: 'NIC', name: 'Nicaragua' },
  { code: 'NE', iso3: 'NER', name: 'Niger' },
  { code: 'NG', iso3: 'NGA', name: 'Nigeria' },
  { code: 'MK', iso3: 'MKD', name: 'North Macedonia' },
  { code: 'NO', iso3: 'NOR', name: 'Norway' },
  { code: 'OM', iso3: 'OMN', name: 'Oman' },
  { code: 'PK', iso3: 'PAK', name: 'Pakistan' },
  { code: 'PW', iso3: 'PLW', name: 'Palau' },
  { code: 'PS', iso3: 'PSE', name: 'Palestine' },
  { code: 'PA', iso3: 'PAN', name: 'Panama' },
  { code: 'PG', iso3: 'PNG', name: 'Papua New Guinea' },
  { code: 'PY', iso3: 'PRY', name: 'Paraguay' },
  { code: 'PE', iso3: 'PER', name: 'Peru' },
  { code: 'PH', iso3: 'PHL', name: 'Philippines' },
  { code: 'PL', iso3: 'POL', name: 'Poland' },
  { code: 'PT', iso3: 'PRT', name: 'Portugal' },
  { code: 'QA', iso3: 'QAT', name: 'Qatar' },
  { code: 'RO', iso3: 'ROU', name: 'Romania' },
  { code: 'RU', iso3: 'RUS', name: 'Russia' },
  { code: 'RW', iso3: 'RWA', name: 'Rwanda' },
  { code: 'KN', iso3: 'KNA', name: 'Saint Kitts and Nevis' },
  { code: 'LC', iso3: 'LCA', name: 'Saint Lucia' },
  { code: 'VC', iso3: 'VCT', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', iso3: 'WSM', name: 'Samoa' },
  { code: 'SM', iso3: 'SMR', name: 'San Marino' },
  { code: 'ST', iso3: 'STP', name: 'Sao Tome and Principe' },
  { code: 'SA', iso3: 'SAU', name: 'Saudi Arabia' },
  { code: 'SN', iso3: 'SEN', name: 'Senegal' },
  { code: 'RS', iso3: 'SRB', name: 'Serbia' },
  { code: 'SC', iso3: 'SYC', name: 'Seychelles' },
  { code: 'SL', iso3: 'SLE', name: 'Sierra Leone' },
  { code: 'SG', iso3: 'SGP', name: 'Singapore' },
  { code: 'SK', iso3: 'SVK', name: 'Slovakia' },
  { code: 'SI', iso3: 'SVN', name: 'Slovenia' },
  { code: 'SB', iso3: 'SLB', name: 'Solomon Islands' },
  { code: 'SO', iso3: 'SOM', name: 'Somalia' },
  { code: 'ZA', iso3: 'ZAF', name: 'South Africa' },
  { code: 'SS', iso3: 'SSD', name: 'South Sudan' },
  { code: 'ES', iso3: 'ESP', name: 'Spain' },
  { code: 'LK', iso3: 'LKA', name: 'Sri Lanka' },
  { code: 'SD', iso3: 'SDN', name: 'Sudan' },
  { code: 'SR', iso3: 'SUR', name: 'Suriname' },
  { code: 'SE', iso3: 'SWE', name: 'Sweden' },
  { code: 'CH', iso3: 'CHE', name: 'Switzerland' },
  { code: 'SY', iso3: 'SYR', name: 'Syria' },
  { code: 'TW', iso3: 'TWN', name: 'Taiwan' },
  { code: 'TJ', iso3: 'TJK', name: 'Tajikistan' },
  { code: 'TZ', iso3: 'TZA', name: 'Tanzania' },
  { code: 'TH', iso3: 'THA', name: 'Thailand' },
  { code: 'TL', iso3: 'TLS', name: 'Timor-Leste' },
  { code: 'TG', iso3: 'TGO', name: 'Togo' },
  { code: 'TO', iso3: 'TON', name: 'Tonga' },
  { code: 'TT', iso3: 'TTO', name: 'Trinidad and Tobago' },
  { code: 'TN', iso3: 'TUN', name: 'Tunisia' },
  { code: 'TR', iso3: 'TUR', name: 'Turkey' },
  { code: 'TM', iso3: 'TKM', name: 'Turkmenistan' },
  { code: 'TV', iso3: 'TUV', name: 'Tuvalu' },
  { code: 'UG', iso3: 'UGA', name: 'Uganda' },
  { code: 'UA', iso3: 'UKR', name: 'Ukraine' },
  { code: 'AE', iso3: 'ARE', name: 'United Arab Emirates' },
  { code: 'GB', iso3: 'GBR', name: 'United Kingdom' },
  { code: 'US', iso3: 'USA', name: 'United States' },
  { code: 'UY', iso3: 'URY', name: 'Uruguay' },
  { code: 'UZ', iso3: 'UZB', name: 'Uzbekistan' },
  { code: 'VU', iso3: 'VUT', name: 'Vanuatu' },
  { code: 'VA', iso3: 'VAT', name: 'Vatican City' },
  { code: 'VE', iso3: 'VEN', name: 'Venezuela' },
  { code: 'VN', iso3: 'VNM', name: 'Vietnam' },
  { code: 'YE', iso3: 'YEM', name: 'Yemen' },
  { code: 'ZM', iso3: 'ZMB', name: 'Zambia' },
  { code: 'ZW', iso3: 'ZWE', name: 'Zimbabwe' }
];

var DINAV_DOOR_OPENER_VISAS = [
  { code: 'USA', iso2: 'US', name: 'United States', visaId: 'US_tourist' },
  { code: 'SCHENGEN', iso2: 'EU', name: 'Schengen (EU)', visaId: 'SCHENGEN_tourist' },
  { code: 'GBR', iso2: 'GB', name: 'United Kingdom', visaId: 'GB_tourist' },
  { code: 'CAN', iso2: 'CA', name: 'Canada', visaId: 'CA_tourist' },
  { code: 'JPN', iso2: 'JP', name: 'Japan', visaId: 'JP_tourist' },
  { code: 'ARE', iso2: 'AE', name: 'UAE', visaId: 'AE_residence' }
];

var DINAV_LOUNGE_OPTIONS = [
  { id: 'priority_pass', name: 'Priority Pass' },
  { id: 'dragon_pass', name: 'Dragon Pass' },
  { id: 'lounge_key', name: 'Lounge Key' }
];

var DINAV_SCHENGEN_MEMBERS = [
  'AUT','BEL','BGR','HRV','CZE','DNK','EST','FIN','FRA','DEU','GRC','HUN','ISL','ITA',
  'LVA','LIE','LTU','LUX','MLT','NLD','NOR','POL','PRT','ROU','SVK','SVN','ESP','SWE','CHE'
];

function getFilteredVisaOptions(passportIso3) {
  return DINAV_DOOR_OPENER_VISAS.filter(function (v) {
    if (v.code === passportIso3) return false;
    if (v.code === 'SCHENGEN' && DINAV_SCHENGEN_MEMBERS.indexOf(passportIso3) !== -1) return false;
    return true;
  });
}

function getCountryByIso3(iso3) {
  for (var i = 0; i < DINAV_COUNTRIES.length; i++) {
    if (DINAV_COUNTRIES[i].iso3.toUpperCase() === iso3.toUpperCase()) return DINAV_COUNTRIES[i];
  }
  return null;
}

function getCountryByCode(code) {
  for (var i = 0; i < DINAV_COUNTRIES.length; i++) {
    if (DINAV_COUNTRIES[i].code.toUpperCase() === code.toUpperCase()) return DINAV_COUNTRIES[i];
  }
  return null;
}
